---
all:
  children:
    windows:
      hosts:
        win11-host:
          ansible_host: 172.22.48.1
          ansible_user: ansible-user
          ansible_password: AnsiblePass123!
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5985
          ansible_winrm_scheme: http
          ansible_winrm_operation_timeout_sec: 60
          ansible_winrm_read_timeout_sec: 70
          ansible_winrm_connection_timeout_sec: 60
