---
# Windows 11 host configuration
ansible_host: 172.22.48.1
ansible_user: ansible-user
ansible_password: AnsiblePass123!
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore
ansible_port: 5985
ansible_winrm_scheme: http
